http:
  routers:
    dashboard:
      rule: Host(`stub.octolab.org`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))
      service: api@internal
      tls:
        certResolver: letsencrypt
      middlewares:
        - auth

    godownloader:
      rule: Host(`godownloader.octolab.org`)
      service: github
      tls:
        certResolver: letsencrypt
      middlewares:
        - redirect-godownloader

    goimports:
      rule: Host(`goimports.octolab.org`)
      service: github
      tls:
        certResolver: letsencrypt
      middlewares:
        - redirect-goimports

    golangci-lint:
      rule: Host(`golangci-lint.octolab.org`)
      service: github
      tls:
        certResolver: letsencrypt
      middlewares:
        - redirect-golangci-lint

    homebrew:
      rule: Host(`homebrew.octolab.org`)
      service: github
      tls:
        certResolver: letsencrypt
      middlewares:
        - redirect-homebrew

    homepage:
      rule: Host(`stub.octolab.org`) && Path(`/`)
      service: github
      tls:
        certResolver: letsencrypt
      middlewares:
        - redirect-stub

    helpmehire:
      rule: Host(`helpmehire.pro`, `www.helpmehire.pro`)
      service: github
      tls:
        certResolver: letsencrypt
      middlewares:
        - redirect-parked

    jointo:
      rule: Host(`jointo.space`, `www.jointo.space`)
      service: github
      tls:
        certResolver: letsencrypt
      middlewares:
        - redirect-parked

    letsbuytogether:
      rule: Host(`letsbuytogether.ru`, `www.letsbuytogether.ru`)
      service: github
      tls:
        certResolver: letsencrypt
      middlewares:
        - redirect-letsbuytogether

    lifeos:
      rule: Host(`lifeos.company`, `www.lifeos.company`)
      service: github
      tls:
        certResolver: letsencrypt
      middlewares:
        - redirect-parked

    octolab:
      rule: Host(`octolab.net`, `www.octolab.net`)
      service: github
      tls:
        certResolver: letsencrypt
      middlewares:
        - redirect-parked

    samigullin:
      rule: Host(`samigullin.info`, `www.samigullin.info`)
      service: github
      tls:
        certResolver: letsencrypt
      middlewares:
        - redirect-samigullin

    tact-cloud:
      rule: Host(`cloud.tact.run`)
      service: github
      tls:
        certResolver: letsencrypt
      middlewares:
        - redirect-tact-cloud


  middlewares:
    auth:
      basicAuth:
        usersFile: /runtime/users

    redirect-godownloader:
      redirectRegex:
        regex: .*
        replacement: https://github.com/kamilsk/godownloader/releases/tag/homebrew

    redirect-goimports:
      redirectRegex:
        regex: .*
        replacement: https://github.com/kamilsk/go-tools/releases/tag/goimports

    redirect-golangci-lint:
      redirectRegex:
        regex: .*
        replacement: https://github.com/kamilsk/golangci-lint/releases/tag/looppointer

    redirect-homebrew:
      redirectRegex:
        regex: .*
        replacement: https://github.com/octolab/homebrew-tap

    redirect-letsbuytogether:
      redirectRegex:
        regex: ^https?://.*/(.*)
        replacement: https://kupitevmeste.ru/${1}

    redirect-parked:
      redirectRegex:
        regex: ^https?://.*/(.*)
        replacement: https://kamil.samigullin.info/${1}

    redirect-samigullin:
      redirectRegex:
        regex: ^https?://.*/(.*)
        replacement: https://kamil.samigullin.info/${1}

    redirect-stub:
      redirectRegex:
        regex: .*
        replacement: https://github.com/octomation/stub

    redirect-tact-cloud:
      redirectRegex:
        regex: .*
        replacement: https://kamilsk.cloud.okteto.net/


  services:
    github:
      loadBalancer:
        servers:
          - url: https://github.com
