http:
  routers:
    dashboard:
      rule: Host(`stub.octolab.org`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))
      service: api@internal
      tls:
        certResolver: letsencrypt
      middlewares:
        - auth

    godownloader:
      rule: Host(`godownloader.octolab.org`)
      service: github
      tls:
        certResolver: letsencrypt
      middlewares:
        - redirect-godownloader

    goimports:
      rule: Host(`goimports.octolab.org`)
      service: github
      tls:
        certResolver: letsencrypt
      middlewares:
        - redirect-goimports

    golangci-lint:
      rule: Host(`golangci-lint.octolab.org`)
      service: github
      tls:
        certResolver: letsencrypt
      middlewares:
        - redirect-golangci-lint

    homebrew:
      rule: Host(`homebrew.octolab.org`)
      service: github
      tls:
        certResolver: letsencrypt
      middlewares:
        - redirect-homebrew


  middlewares:
    auth:
      basicAuth:
        usersFile: /runtime/users

    redirect-godownloader:
      redirectRegex:
        regex: .*
        replacement: https://github.com/kamilsk/godownloader/releases/tag/homebrew

    redirect-goimports:
      redirectRegex:
        regex: .*
        replacement: https://github.com/kamilsk/go-tools/releases/tag/goimports

    redirect-golangci-lint:
      redirectRegex:
        regex: .*
        replacement: https://github.com/kamilsk/golangci-lint/releases/tag/looppointer

    redirect-homebrew:
      redirectRegex:
        regex: .*
        replacement: https://github.com/octolab/homebrew-tap

  services:
    github:
      loadBalancer:
        servers:
          - url: https://github.com
