http:
  services:
    github:
      loadBalancer:
        servers:
          - url: https://github.com

  middlewares:
    redirect-github:
      redirectRegex:
        regex: .*
        replacement: https://github.com/octolab
