http:
  routers:
    jointo:
      rule: Host(`jointo.space`, `www.jointo.space`)
      service: github
      tls:
        certResolver: letsencrypt
      middlewares:
        - redirect-to-kamilsk-on-cal.com
        - redirect-to-kamilsk-on-getmentor
        - redirect-to-kamilsk-on-github
        - redirect-to-kamilsk-on-linkedin
        - redirect-to-kamilsk-on-telegram
        - redirect-to-kamilsk-on-twitter
        - redirect-parked

  middlewares:
    redirect-to-kamilsk-on-cal.com:
      redirectRegex:
        regex: ^.*jointo\.space/kamilsk/cal\.com(.*)$
        replacement: https://cal.com/kamilsk${1}

    redirect-to-kamilsk-on-getmentor:
      redirectRegex:
        regex: ^.*jointo\.space/kamilsk/getmentor$
        replacement: https://getmentor.dev/mentor/kamil-samigullin-612

    redirect-to-kamilsk-on-github:
      redirectRegex:
        regex: ^.*jointo\.space/kamilsk/github$
        replacement: https://github.com/kamilsk

    redirect-to-kamilsk-on-linkedin:
      redirectRegex:
        regex: ^.*jointo\.space/kamilsk/linkedin$
        replacement: https://www.linkedin.com/in/kamilsk/

    redirect-to-kamilsk-on-telegram:
      redirectRegex:
        regex: ^.*jointo\.space/kamilsk/telegram$
        replacement: https://t.me/kamilsk

    redirect-to-kamilsk-on-twitter:
      redirectRegex:
        regex: ^.*jointo\.space/kamilsk/twitter$
        replacement: https://twitter.com/ikamilsk
