http:
  routers:
    lifeos:
      rule: Host(`lifeos.company`, `www.lifeos.company`)
      service: github
      tls:
        certResolver: letsencrypt
      middlewares:
        - redirect-to-lifeos-on-github

  middlewares:
    redirect-to-lifeos-on-github:
      redirectRegex:
        regex: .*
        replacement: https://github.com/lifeosm
