http:
  routers:
    makefiles:
      rule: Host(`makefiles.octolab.org`)
      service: github
      tls:
        certResolver: letsencrypt
      middlewares:
        - redirect-makefiles

  middlewares:
    redirect-makefiles:
      redirectRegex:
        regex: .*
        replacement: https://github.com/octomation/makefiles
