http:
  routers:
    octolab.org:
      rule: Host(
          `octolab.org`,
          `www.octolab.org`,
          `blog.octolab.org`,
          `idea.octolab.org`,
        )
      service: github
      tls:
        certResolver: letsencrypt
      middlewares:
        - redirect-github
