http:
  routers:
    samigullin:
      rule: Host(
          `kamil.samigullin.info`,
          `samigullin.info`,
          `www.samigullin.info`,
        )
      service: github
      tls:
        certResolver: letsencrypt
      middlewares:
        - redirect-parked
