http:
  routers:
    sparkle:
      rule: Host(`sparkle.wiki`, `www.sparkle.wiki`)
      service: github
      tls:
        certResolver: letsencrypt
      middlewares:
        - redirect-to-sparkle-on-github

  middlewares:
    redirect-to-sparkle-on-github:
      redirectRegex:
        regex: .*
        replacement: https://github.com/withsparkle
