http:
  routers:
    dashboard:
      rule: Host(`stub.octolab.org`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))
      service: api@internal
      tls:
        certResolver: letsencrypt
      middlewares:
        - auth
    homepage:
      rule: Host(`stub.octolab.org`) && Path(`/`)
      service: github
      tls:
        certResolver: letsencrypt
      middlewares:
        - redirect-stub

  middlewares:
    auth:
      basicAuth:
        usersFile: /runtime/users

    redirect-stub:
      redirectRegex:
        regex: .*
        replacement: https://github.com/octomation/stub
