http:
  routers:
    tact:
      rule: Host(`tact.run`, `www.tact.run`)
      service: github
      tls:
        certResolver: letsencrypt
      middlewares:
        - redirect-to-tact-on-github

    tact-cloud:
      rule: Host(`cloud.tact.run`)
      service: github
      tls:
        certResolver: letsencrypt
      middlewares:
        - redirect-to-tact-at-okteto

  middlewares:
    redirect-to-tact-on-github:
      redirectRegex:
        regex: .*
        replacement: https://github.com/tact-app

    redirect-to-tact-at-okteto:
      redirectRegex:
        regex: .*
        replacement: https://kamilsk.cloud.okteto.net/
