http:
  routers:
    godownloader:
      rule: Host(`godownloader.octolab.org`)
      service: github
      tls:
        certResolver: letsencrypt
      middlewares:
        - redirect-godownloader

  middlewares:
    redirect-godownloader:
      redirectRegex:
        regex: .*
        replacement: https://github.com/kamilsk/godownloader/releases/tag/homebrew
