http:
  routers:
    www.octolab.org:
      rule: Host(`www.octolab.org`, `octolab.org`)
      service: github
      tls:
        certResolver: letsencrypt
      middlewares:
        - redirect-github
